image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run PetClinic app
    init: ./mvnw -B dependency:go-offline package -DskipTests
    command: java -jar target/*.jar
    openMode: split-left
  - name: Start Tailscale
    command: |
      screen -d -m sudo tailscaled --state=mem:
      sudo -E tailscale up --accept-dns --accept-routes --hostname "DEMO-${GITPOD_WORKSPACE_ID}" --authkey=$TS_AUTHKEY
    openMode: split-right
  - name: shell
    command: /usr/bin/bash
    openMode: tab-after

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: true
    addBadge: true
