image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run PetClinic app
    init: ./mvnw -B dependency:go-offline package -DskipTests
    command: |
      alias test_no_sql="mvn spring-boot:run"
      alias test_mysql="mvn spring-boot:run -Dspring-boot.run.profiles=mysql"
      test_no_sql
  - name: Start Tailscale & preflights
    command: |
      screen -d -m sudo tailscaled --state=mem:
      gpg --keyserver keys.openpgp.org --recv-keys $GPG_ID
      gpgconf --kill gpg-agent
      git config --global user.signingkey $GPG_ID
      sudo -E tailscale up --accept-dns --accept-routes --hostname "DEMO-${GITPOD_WORKSPACE_ID}" --authkey=$TS_AUTHKEY

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: true
    addBadge: true
