image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Tailscale
    command: |
      screen -d -m sudo tailscaled --state=mem:
      sudo -E tailscale up --accept-dns --advertise-tags=tag:cs-node --accept-routes
  - init: ./mvnw -B dependency:go-offline package -DskipTests
    command: java -jar target/*.jar
    name: Run PetClinic app

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
    - redhat.java

